apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    appstudio.redhat.com/updateComponentOnSuccess: "false"
  creationTimestamp: null
  labels:
    pipelines.openshift.io/runtime: generic
    pipelines.openshift.io/strategy: docker
    pipelines.openshift.io/used-by: build-cloud
  name: docker-build
spec:
  finally:
  - name: show-summary
    params:
    - name: pipeline-run-name
      value: $(context.pipelineRun.name)
    - name: git-url
      value: $(params.git-url)
    - name: image-url
      value: $(params.output-image)
    taskRef:
      bundle: quay.io/redhat-appstudio/appstudio-tasks:748a03507b68aa610212e8031e3301ab943a14ef-2@sha256:de38a62826928913d5a30ba5e399fc58fe68c39c8eded5edb3ef38b4d54c554b
      name: summary
  - name: hacbs-test-evaluation
    params:
    - name: BASE_IMAGE
      value: $(tasks.sanity-inspect-image.results.BASE_IMAGE)
    taskRef:
      bundle: quay.io/redhat-appstudio/appstudio-tasks:748a03507b68aa610212e8031e3301ab943a14ef-1@sha256:007f3e67f21633e04cf164e56327306e4ac737a07637dffed12c5c033a53b81d
      name: hacbs-test-evaluation
    workspaces:
    - name: workspace
      workspace: workspace
  - name: infra-deployments-mr
    params:
    - name: ORIGIN_REPO
      value: $(params.git-url)
    - name: REVISION
      value: $(params.revision)
    - name: SCRIPT
      value: $(params.infra-deployment-update-script)
    taskRef:
      bundle: quay.io/redhat-appstudio/appstudio-tasks:748a03507b68aa610212e8031e3301ab943a14ef-2@sha256:de38a62826928913d5a30ba5e399fc58fe68c39c8eded5edb3ef38b4d54c554b
      name: update-infra-deployments
    when:
    - input: $(params.infra-deployment-update-script)
      operator: notin
      values:
      - ""
    - input: $(tasks.status)
      operator: notin
      values:
      - Failed
  params:
  - description: Source Repository URL
    name: git-url
    type: string
  - default: ""
    description: Revision of the Source Repository
    name: revision
    type: string
  - description: Fully Qualified Output Image
    name: output-image
    type: string
  - default: .
    description: The path to your source code
    name: path-context
    type: string
  - default: Dockerfile
    description: Path to the Dockerfile
    name: dockerfile
    type: string
  - default: "true"
    description: Force rebuild image
    name: rebuild
    type: string
  - default: ""
    name: infra-deployment-update-script
  results:
  - description: ""
    name: IMAGE_URL
    value: $(tasks.build-container.results.IMAGE_URL)
  - description: ""
    name: IMAGE_DIGEST
    value: $(tasks.build-container.results.IMAGE_DIGEST)
  - description: ""
    name: CHAINS-GIT_URL
    value: $(tasks.clone-repository.results.url)
  - description: ""
    name: CHAINS-GIT_COMMIT
    value: $(tasks.clone-repository.results.commit)
  tasks:
  - name: appstudio-init
    params:
    - name: image-url
      value: $(params.output-image)
    - name: rebuild
      value: $(params.rebuild)
    - name: jvm-build-service-init
      value: "true"
    taskRef:
      bundle: quay.io/redhat-appstudio/appstudio-tasks:748a03507b68aa610212e8031e3301ab943a14ef-2@sha256:de38a62826928913d5a30ba5e399fc58fe68c39c8eded5edb3ef38b4d54c554b
      name: init
  - name: clone-repository
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
    runAfter:
    - appstudio-init
    taskRef:
      bundle: quay.io/redhat-appstudio/appstudio-tasks:748a03507b68aa610212e8031e3301ab943a14ef-1@sha256:007f3e67f21633e04cf164e56327306e4ac737a07637dffed12c5c033a53b81d
      name: git-clone
    when:
    - input: $(tasks.appstudio-init.results.build)
      operator: in
      values:
      - "true"
    workspaces:
    - name: output
      workspace: workspace
    - name: basic-auth
      workspace: git-auth
  - name: appstudio-configure-build
    params:
    - name: shared-secret
      value: redhat-appstudio-staginguser
    runAfter:
    - clone-repository
    taskRef:
      bundle: quay.io/redhat-appstudio/appstudio-tasks:748a03507b68aa610212e8031e3301ab943a14ef-1@sha256:007f3e67f21633e04cf164e56327306e4ac737a07637dffed12c5c033a53b81d
      name: configure-build
    when:
    - input: $(tasks.appstudio-init.results.build)
      operator: in
      values:
      - "true"
    workspaces:
    - name: source
      workspace: workspace
    - name: registry-auth
      workspace: registry-auth
  - name: build-container
    params:
    - name: IMAGE
      value: $(params.output-image)
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    - name: BUILD_EXTRA_ARGS
      value: $(tasks.appstudio-configure-build.results.buildah-auth-param)
    - name: PUSH_EXTRA_ARGS
      value: $(tasks.appstudio-configure-build.results.buildah-auth-param)
    - name: MAVEN_MIRROR_URL
      value: http://localhost:2000/maven2
    runAfter:
    - appstudio-configure-build
    taskRef:
      bundle: quay.io/redhat-appstudio/appstudio-tasks:748a03507b68aa610212e8031e3301ab943a14ef-1@sha256:007f3e67f21633e04cf164e56327306e4ac737a07637dffed12c5c033a53b81d
      name: buildah
    when:
    - input: $(tasks.appstudio-init.results.build)
      operator: in
      values:
      - "true"
    workspaces:
    - name: source
      workspace: workspace
  - name: sanity-inspect-image
    params:
    - name: IMAGE_URL
      value: $(params.output-image)
    runAfter:
    - build-container
    taskRef:
      bundle: quay.io/redhat-appstudio/appstudio-tasks:748a03507b68aa610212e8031e3301ab943a14ef-2@sha256:de38a62826928913d5a30ba5e399fc58fe68c39c8eded5edb3ef38b4d54c554b
      name: sanity-inspect-image
    workspaces:
    - name: workspace
      workspace: workspace
  - name: sanity-label-check
    runAfter:
    - sanity-inspect-image
    taskRef:
      bundle: quay.io/redhat-appstudio/appstudio-tasks:748a03507b68aa610212e8031e3301ab943a14ef-2@sha256:de38a62826928913d5a30ba5e399fc58fe68c39c8eded5edb3ef38b4d54c554b
      name: sanity-label-check
    workspaces:
    - name: workspace
      workspace: workspace
  - name: sanity-optional-label-check
    params:
    - name: POLICY_NAMESPACE
      value: optional_checks
    runAfter:
    - sanity-inspect-image
    taskRef:
      bundle: quay.io/redhat-appstudio/appstudio-tasks:748a03507b68aa610212e8031e3301ab943a14ef-2@sha256:de38a62826928913d5a30ba5e399fc58fe68c39c8eded5edb3ef38b4d54c554b
      name: sanity-label-check
    workspaces:
    - name: workspace
      workspace: workspace
  - name: deprecated-base-image-check
    params:
    - name: IMAGE_REGISTRY
      value: registry.access.redhat.com
    - name: IMAGE_REPOSITORY
      value: $(tasks.sanity-inspect-image.results.BASE_IMAGE_REPOSITORY)
    runAfter:
    - sanity-inspect-image
    taskRef:
      bundle: quay.io/redhat-appstudio/appstudio-tasks:748a03507b68aa610212e8031e3301ab943a14ef-1@sha256:007f3e67f21633e04cf164e56327306e4ac737a07637dffed12c5c033a53b81d
      name: deprecated-image-check
    workspaces:
    - name: sanity-ws
      workspace: workspace
  - name: get-clair-results
    params:
    - name: image-digest
      value: $(tasks.build-container.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-container.results.IMAGE_URL)
    runAfter:
    - build-container
    taskRef:
      bundle: quay.io/redhat-appstudio/appstudio-tasks:748a03507b68aa610212e8031e3301ab943a14ef-1@sha256:007f3e67f21633e04cf164e56327306e4ac737a07637dffed12c5c033a53b81d
      name: get-clair-scan
    workspaces:
    - name: clair-ws
      workspace: workspace
    - name: registry-auth
      workspace: registry-auth
  - name: conftest-clair
    runAfter:
    - get-clair-results
    taskRef:
      bundle: quay.io/redhat-appstudio/appstudio-tasks:748a03507b68aa610212e8031e3301ab943a14ef-1@sha256:007f3e67f21633e04cf164e56327306e4ac737a07637dffed12c5c033a53b81d
      name: conftest-clair
    workspaces:
    - name: conftest-ws
      workspace: workspace
  - name: sast-snyk-check
    runAfter:
    - clone-repository
    taskRef:
      bundle: quay.io/redhat-appstudio/appstudio-tasks:748a03507b68aa610212e8031e3301ab943a14ef-2@sha256:de38a62826928913d5a30ba5e399fc58fe68c39c8eded5edb3ef38b4d54c554b
      name: sast-snyk-check
    workspaces:
    - name: workspace
      workspace: workspace
  - name: clamav-scan
    params:
    - name: image-digest
      value: $(tasks.build-container.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-container.results.IMAGE_URL)
    runAfter:
    - build-container
    taskRef:
      bundle: quay.io/redhat-appstudio/appstudio-tasks:748a03507b68aa610212e8031e3301ab943a14ef-1@sha256:007f3e67f21633e04cf164e56327306e4ac737a07637dffed12c5c033a53b81d
      name: clamav-scan
    workspaces:
    - name: registry-auth
      workspace: registry-auth
  workspaces:
  - name: workspace
  - name: registry-auth
    optional: true
  - name: git-auth
    optional: true